INSERT INTO Context (id, name) VALUES (1, "tpro")
INSERT INTO Permission(id, name, context_id) VALUES (1, 'admin', 1)
INSERT INTO Permission(id, name, context_id) VALUES (2, 'user', 1)
INSERT INTO User (id, prename, surname, username, email, password) VALUES (1, "Max", "Mustermann", "admin", "mustermax@tpro.de", "admin")
INSERT INTO User (id, prename, surname, username, email, password) VALUES (2, "Maxime", "Musterfrau", "user", "mustermaxime@tpro.de", "user")
INSERT INTO User_Permission (user_id, permission_id) VALUES (1, 1)
INSERT INTO User_Permission (user_id, permission_id) VALUES (2, 2)
-- User Management Test Data 
INSERT INTO Context (id, name) VALUES (2, "Uni")
INSERT INTO Permission(id, name, context_id) VALUES (3, 'Teacher', 2)
INSERT INTO Permission(id, name, context_id) VALUES (4, 'Student', 2)
INSERT INTO Permission(id, name, context_id) VALUES (5, 'Guest', 2)
INSERT INTO Permission(id, name, context_id) VALUES (6, 'Caretaker', 2)
-- Testdaten, um Permissions zu löschen, die Usern zugewiesen sind!
--INSERT INTO User (id, prename, surname, username, email, password) VALUES (3, "Lisa", "Musterfrau", "lisa", "musterlisa@tpro.de", "lisa")
--INSERT INTO User_Permission (user_id, permission_id) VALUES (3, 6)