# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7.21
        environment:
        - MYSQL_USER=tpro
        - MYSQL_PASSWORD=tpro
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/tpro-core

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - run:
          # Add a password to the `ubuntu` user, since Postgres is configured to
          # always ask for a password without sudo, and fails without one.
          command: sudo cat /ect/passwd
          command: sudo -u mysqld mysql -utpro -ptpro -e 'CREATE DATABASE test_tpro_user_management;'

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - tpro-core-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - tpro-core-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tpro-core-{{ checksum "pom.xml" }}
        
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/tpro.war
